Invoke-Expression "scp -i C:\Users\laarz\.ssh\strato -r C:\Users\laarz\Documents\Website\Piepscave\content root@82.165.60.161:/var/www/piepscave"
Invoke-Expression "scp -i C:\Users\laarz\.ssh\strato -r C:\Users\laarz\Documents\Website\Piepscave\dist root@82.165.60.161:/var/www/piepscave"
Invoke-Expression "scp -i C:\Users\laarz\.ssh\strato -r C:\Users\laarz\Documents\Website\Piepscave\index.html root@82.165.60.161:/var/www/piepscave"
Invoke-Expression "scp -i C:\Users\laarz\.ssh\strato -r C:\Users\laarz\Documents\Website\Piepscave\style.css root@82.165.60.161:/var/www/piepscave"
Invoke-Expression "scp -i C:\Users\laarz\.ssh\strato -r C:\Users\laarz\Documents\Website\Piepscave\icon\* root@82.165.60.161:/var/www/piepscave/icon"